# Generated by Django 6.0.1 on 2026-07-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=100, verbose_name='Équipe à domicile')),
                ('away_team', models.CharField(max_length=100, verbose_name="Équipe à l'extérieur")),
                ('match_date', models.DateField(verbose_name='Date du match')),
                ('neutral', models.BooleanField(default=True, verbose_name='Terrain neutre')),
                ('home_fifa_rank', models.FloatField()),
                ('away_fifa_rank', models.FloatField()),
                ('home_fifa_points', models.FloatField()),
                ('away_fifa_points', models.FloatField()),
                ('predicted_result', models.CharField(choices=[('home_win', 'Victoire domicile'), ('draw', 'Match nul'), ('away_win', 'Victoire extérieure')], max_length=20)),
                ('home_win_probability', models.FloatField()),
                ('draw_probability', models.FloatField()),
                ('away_win_probability', models.FloatField()),
                ('confidence_level', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée')], max_length=10)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-predicted_at'],
            },
        ),
    ]
