# Generated by Django 6.0.1 on 2026-07-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchprediction',
            name='tournament',
            field=models.CharField(choices=[('FIFA World Cup', 'Coupe du monde FIFA'), ('FIFA World Cup qualification', 'Qualifications Coupe du monde'), ('Friendly', 'Match amical'), ('UEFA Euro', "Championnat d'Europe UEFA"), ('UEFA Euro qualification', 'Qualifications Euro UEFA'), ('African Cup of Nations', "Coupe d'Afrique des nations"), ('African Cup of Nations qualification', "Qualifications Coupe d'Afrique"), ('Copa América', 'Copa América'), ('AFC Asian Cup', "Coupe d'Asie AFC"), ('AFC Asian Cup qualification', "Qualifications Coupe d'Asie"), ('Gold Cup', 'Gold Cup CONCACAF'), ('Oceania Nations Cup', "Coupe d'Océanie"), ('UEFA Nations League', 'Ligue des nations UEFA'), ('CONCACAF Nations League', 'Ligue des nations CONCACAF'), ('Confederations Cup', 'Coupe des confédérations')], default='FIFA World Cup', max_length=100, verbose_name="Type d'événement"),
        ),
    ]
