# Generated by Django 6.0.1 on 2026-07-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_matchprediction_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchprediction',
            name='predicted_away_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchprediction',
            name='predicted_home_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
